INSERT INTO project.products (product_id, description, name, price, quantity, status, category_category_id) VALUES (1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras semper sit amet nisi non interdum. Sed semper tortor consectetur orci tempus imperdiet. Ut purus quam, lacinia ullamcorper dolor et, pellentesque auctor nisi. ', 'Konsola Xbox Series X 1TB', 2249.00, 100, true, 1);
INSERT INTO project.products (product_id, description, name, price, quantity, status, category_category_id) VALUES (2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras semper sit amet nisi non interdum. Sed semper tortor consectetur orci tempus imperdiet. Ut purus quam, lacinia ullamcorper dolor et, pellentesque auctor nisi. ', 'Konsola Xbox Series S 500GB', 1349.00, 100, true, 1);
INSERT INTO project.products (product_id, description, name, price, quantity, status, category_category_id) VALUES (3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras semper sit amet nisi non interdum. Sed semper tortor consectetur orci tempus imperdiet. Ut purus quam, lacinia ullamcorper dolor et, pellentesque auctor nisi. ', 'iPhone 11 Pro 256GB gwiezdna szarosc', 3899.00, 100, true, 2);
INSERT INTO project.products (product_id, description, name, price, quantity, status, category_category_id) VALUES (4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras semper sit amet nisi non interdum. Sed semper tortor consectetur orci tempus imperdiet. Ut purus quam, lacinia ullamcorper dolor et, pellentesque auctor nisi. ', 'iPhone 11 64GB Czarny', 3389.00, 100, true, 2);
INSERT INTO project.products (product_id, description, name, price, quantity, status, category_category_id) VALUES (5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras semper sit amet nisi non interdum. Sed semper tortor consectetur orci tempus imperdiet. Ut purus quam, lacinia ullamcorper dolor et, pellentesque auctor nisi. ', 'IPhone SE 128GB 4,7'''' Czarny', 1999.00, 100, true, 2);
INSERT INTO project.products (product_id, description, name, price, quantity, status, category_category_id) VALUES (6, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras semper sit amet nisi non interdum. Sed semper tortor consectetur orci tempus imperdiet. Ut purus quam, lacinia ullamcorper dolor et, pellentesque auctor nisi. ', 'iPad Pro 11" 512 GB Wi-Fi + LTE', 4599.00, 100, true, 3);
INSERT INTO project.products (product_id, description, name, price, quantity, status, category_category_id) VALUES (7, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras semper sit amet nisi non interdum. Sed semper tortor consectetur orci tempus imperdiet. Ut purus quam, lacinia ullamcorper dolor et, pellentesque auctor nisi. ', 'iPad Air 10,9', 2499.00, 100, true, 3);
INSERT INTO project.products (product_id, description, name, price, quantity, status, category_category_id) VALUES (8, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras semper sit amet nisi non interdum. Sed semper tortor consectetur orci tempus imperdiet. Ut purus quam, lacinia ullamcorper dolor et, pellentesque auctor nisi.', 'Pad 10,2', 1599.00, 100, true, 3);
INSERT INTO project.products (product_id, description, name, price, quantity, status, category_category_id) VALUES (9, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras semper sit amet nisi non interdum. Sed semper tortor consectetur orci tempus imperdiet. Ut purus quam, lacinia ullamcorper dolor et, pellentesque auctor nisi. ', 'Apple Watch 6 GPS  Aluminium 44mm', 2299.00, 100, true, 4);


INSERT INTO project.product_images (product_product_id, images_id) VALUES (1, 1);
INSERT INTO project.product_images (product_product_id, images_id) VALUES (2, 2);
INSERT INTO project.product_images (product_product_id, images_id) VALUES (3, 3);
INSERT INTO project.product_images (product_product_id, images_id) VALUES (4, 4);
INSERT INTO project.product_images (product_product_id, images_id) VALUES (5, 5);
INSERT INTO project.product_images (product_product_id, images_id) VALUES (6, 6);
INSERT INTO project.product_images (product_product_id, images_id) VALUES (7, 7);
INSERT INTO project.product_images (product_product_id, images_id) VALUES (8, 8);
INSERT INTO project.product_images (product_product_id, images_id) VALUES (9, 9);
